[pytest]
# Регистрация маркеров для раздельного запуска тестов (UI / API / Все)
markers =
    ui: Тесты пользовательского интерфейса (Selenium)
    api: Тесты программного интерфейса (Requests)

# Настройки консольного вывода и логов
addopts = --alluredir=allure-results -v
log_cli = true
log_cli_level = INFO

# Указываем корень проекта для корректного поиска импортов
pythonpath = .
